### ISSUE TITLE
fails to build when added as a stack dependency

### ISSUE THREAD

**Issue by o1lo01ol1o** [gagandeepb/Frames-beam#19]
upon building my project:

```haskell
• Couldn't match kind ‘*’
                         with ‘(ghc-prim-0.5.1.1:GHC.Types.Symbol, *)’
          When matching the kind of ‘ZipTypes b_names b_rs’
          Expected type: b Identity
                         -> Frames.Rec.Record (ZipTypes b_names b_rs)
            Actual type: b Identity
                         -> Data.Vinyl.Core.Rec
                              Data.Vinyl.Functor.Identity (ZipTypes b_names b_rs)
        • In the first argument of ‘map’, namely ‘createRecId’
          In the expression: map createRecId bQRes
          In an equation for ‘bRecs’: bRecs = map createRecId bQRes
        • Relevant bindings include
            bRecs :: [Frames.Rec.Record (ZipTypes b_names b_rs)]
              (bound at src/Frames/SQL/Beam/Postgres/Query.hs:66:5)
            join2 :: JoinQueryResults a b
                     -> FrameRec (ZipTypes a_names a_rs ++ ZipTypes b_names b_rs)
              (bound at src/Frames/SQL/Beam/Postgres/Query.hs:61:1)
```

using this `stack.yaml`
```yaml
resolver: lts-11.7
packages:
- .
extra-deps:
- Frames-0.5.0
- beam-core-0.7.2.2
- beam-migrate-0.3.2.1
- beam-postgres-0.3.2.2
- vinyl-0.10.0
- Frames-beam-0.1.0.1
```
